receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins: ["*"]
          allowed_headers: ["*"]

  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 30s    # Moderado
          static_configs:
            - targets: ['localhost:8888']

processors:
  # Memory limiter ajustado para 1.2GB total
  memory_limiter:
    limit_mib: 1000         # Límite conservador dentro del contenedor
    spike_limit_mib: 200    # Spike razonable
    check_interval: 200ms   # Chequeo frecuente pero no excesivo

  # Batch processor equilibrado
  batch:
    timeout: 200ms          # Balance entre latencia y throughput
    send_batch_size: 1000   # Lotes medianos
    send_batch_max_size: 2000

  resource:
    attributes:
      - key: otel.service.name
        from_attribute: service.name
        action: upsert
      - key: otel.service.version
        from_attribute: service.version
        action: upsert

exporters:
  # Tempo OK
  otlp/tempo:
    endpoint: http://tempo:4317
    tls:
      insecure: true

  # Loki OK
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  # Prometheus moderado
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "pltelemetry"
    send_timestamps: true
    metric_expiration: 60m      # 1 hora - balance memoria/utilidad
    resource_to_telemetry_conversion:
      enabled: false
    enable_open_metrics: true

  # Debug muy limitado
  debug:
    verbosity: basic
    sampling_initial: 1
    sampling_thereafter: 1000   # Muy poco verbose

service:
  # 🔧 FIX: Telemetry sin address (inválido)
  telemetry:
    logs:
      level: "warn"
    metrics:
      level: "basic"
      # ❌ QUITAR: address: "0.0.0.0:8888"  <- ESTO ESTÁ MAL

  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlp/tempo]

    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, resource, batch]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [loki]
