-- src/ddl/01_tables.sql
PROMPT [DDL] Creating Tables and Indexes...

-- 1. CLEANUP
DECLARE
    l_sql VARCHAR2(1000);
BEGIN
    FOR rec IN (
        SELECT table_name 
        FROM user_tables 
        WHERE table_name IN (
            'PLT_TRACES', 'PLT_SPANS', 'PLT_EVENTS', 'PLT_METRICS', 
            'PLT_LOGS', 'PLT_SPAN_ATTRIBUTES', 'PLT_FAILED_EXPORTS', 
            'PLT_SERVICE_DISCOVERY_CONFIG', 'PLT_SERVICE_DISCOVERY_CRIT_LEVELS',
            'PLT_FAILOVER_CONFIG', 'DB_VALIDATION_RESULTS', 'DB_VALIDATION_RULES',
            'DB_VALIDATION_TYPES',
            'PLT_QUEUE', 'PLT_PULSE_THROTTLING_CONFIG', 
            'PLT_AGENT_REGISTRY', 'PLT_TELEMETRY_ERRORS'
        )
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || rec.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
    
    FOR s IN (SELECT sequence_name FROM user_sequences WHERE sequence_name = 'PLT_QUEUE_SEQ') LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
    END LOOP;
END;
/

-- 2. TABLES & INDEXES
-- 1. PLT_QUEUE (Vital)
CREATE TABLE plt_queue (
    id              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    item_type       VARCHAR2(20) NOT NULL,
    payload         CLOB         NOT NULL,
    status          VARCHAR2(20) DEFAULT 'NEW' NOT NULL,
    retry_count     NUMBER       DEFAULT 0     NOT NULL,
    error_message   VARCHAR2(4000),
    created_at      TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
    tenant_id       VARCHAR2(100) DEFAULT 'default', -- <--- AQUÍ ES CRÍTICO
    CONSTRAINT chk_plt_queue_type CHECK (item_type IN ('TRACE', 'METRIC', 'LOG')),
    CONSTRAINT chk_plt_queue_status CHECK (status IN ('NEW', 'PROCESSING', 'FAILED', 'PROCESSED'))
);
-- Índice compuesto para que el Agente pueda filtrar por tenant rápido si quiere
CREATE INDEX idx_plt_queue_main ON plt_queue(status, tenant_id, id); 

-- 2. PLT_PULSE_THROTTLING_CONFIG (Futuro-proof)
CREATE TABLE plt_pulse_throttling_config (
    pulse_mode          VARCHAR2(10),
    tenant_id           VARCHAR2(100) DEFAULT 'GLOBAL', -- <--- AÑADIDO (PK compuesta)
    capacity_multiplier NUMBER(5,4) NOT NULL,
    batch_multiplier    NUMBER(5,4) NOT NULL, 
    interval_multiplier NUMBER(5,2) NOT NULL,
    sampling_rate       NUMBER(5,4) NOT NULL,
    metrics_enabled     VARCHAR2(1) DEFAULT 'Y',
    logs_enabled        VARCHAR2(1) DEFAULT 'Y',
    queue_processing    VARCHAR2(1) DEFAULT 'Y',
    description         VARCHAR2(200),
    is_active           VARCHAR2(1) DEFAULT 'Y',
    CONSTRAINT pk_plt_pulse_config PRIMARY KEY (pulse_mode, tenant_id) -- PK incluye tenant
);

-- 3. PLT_AGENT_REGISTRY (Infraestructura - Opcional)
CREATE TABLE plt_agent_registry (
    agent_id          VARCHAR2(100) DEFAULT 'PRIMARY' PRIMARY KEY,
    last_heartbeat    TIMESTAMP WITH TIME ZONE,
    last_process_time TIMESTAMP WITH TIME ZONE,
    items_processed   NUMBER DEFAULT 0,
    status_message    VARCHAR2(4000),
    version           VARCHAR2(50),
    created_at        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP,
    updated_at        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP
    -- Aquí NO pongo tenant_id porque el agente suele ser global
);

-- 4. PLT_TELEMETRY_ERRORS (Debug Contextual)
CREATE TABLE plt_telemetry_errors (
    error_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    error_time    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    error_message VARCHAR2(4000),
    error_stack   VARCHAR2(4000),
    module_name   VARCHAR2(100),
    trace_id      VARCHAR2(32),
    span_id       VARCHAR2(16),  -- <--- Añado Span ID también, muy útil
    tenant_id     VARCHAR2(100)  -- <--- AÑADIDO (Vital para saber a quién culpar)
);